"""The plumber.

Frames are not hand-authored one by one: a small rig draws a body from pose data (hip,
shoulder, hand and foot anchors per pose), and cycles such as running are generated by
sampling limb endpoints along a sine, which gives a smooth stride for free.
"""
from __future__ import annotations

import math

from ..engine.assets import asset, register
from ..engine.ink import Canvas, hexc, mix

SKIN = hexc("#f2b98a")
SKIN_D = hexc("#c8794a")
HAIR = hexc("#4b2a12")
RED = hexc("#e0392b")
BLUE = hexc("#2f5ecf")
SHOE = hexc("#6a3a17")
WHITE = hexc("#f6f2ea")
GOLD = hexc("#f6c95c")
EYE = hexc("#2a2a3a")


def _limb(c: Canvas, a, b, w, color, joint=None):
    c.line([a, b], w, color)
    c.ellipse((b[0] - w / 2, b[1] - w / 2, b[0] + w / 2 - 0.5, b[1] + w / 2 - 0.5), joint or color)


def plumber(h: int, pose: dict, shirt=RED, over=BLUE, cap=RED, hair=HAIR) -> Canvas:
    """Draw one frame. ``pose`` holds normalized anchors (0..1 of the sprite box)."""
    w = max(10, int(h * 0.72))
    c = Canvas((w, h))
    P = lambda p: ((p[0] * w + 0.5, p[1] * h + 0.5))  # noqa: E731 - normalized -> px
    lean = pose.get("lean", 0.0) * w
    hip = P(pose.get("hip", (0.5, 0.70)))
    shoulder = (hip[0] + lean, hip[1] - h * 0.30)
    head_c = (shoulder[0] + lean * 0.4, shoulder[1] - h * 0.16)
    head_r = h * (0.24 if h > 18 else 0.30)

    # legs + shoes
    for key, back in (("leg_b", True), ("leg_f", False)):
        foot = P(pose[key])
        col = mix(BLUE, (0, 0, 0, 0), 0) if not back else mix(BLUE, (0, 0, 0, 0), 0)
        _limb(c, (hip[0] - (2 if back else -2), hip[1]), foot, h * 0.16,
              mix(BLUE, (10, 10, 20, 255), 0.0 if not back else 0.25))
        c.rrect((foot[0] - h * 0.13, foot[1] - h * 0.06, foot[0] + h * 0.16, foot[1] + h * 0.05),
                h * 0.06, mix(SHOE, (0, 0, 0, 255), 0.15 if back else 0.0))
    # torso: shirt then overalls bib
    c.poly([(shoulder[0] - w * 0.24, shoulder[1]), (shoulder[0] + w * 0.24, shoulder[1]),
            (hip[0] + w * 0.20, hip[1]), (hip[0] - w * 0.20, hip[1])], shirt)
    c.poly([(hip[0] - w * 0.19, hip[1] - h * 0.12), (hip[0] + w * 0.19, hip[1] - h * 0.12),
            (hip[0] + w * 0.20, hip[1]), (hip[0] - w * 0.20, hip[1])], over)
    # back arm, then head, then front arm (keeps overlaps readable)
    _limb(c, (shoulder[0] - w * 0.18, shoulder[1]), P(pose["arm_b"]), h * 0.13,
          mix(shirt, (0, 0, 0, 255), 0.2), WHITE)
    c.ellipse((head_c[0] - head_r, head_c[1] - head_r * 0.9, head_c[0] + head_r * 0.95,
               head_c[1] + head_r * 0.8), SKIN)
    c.pie((head_c[0] - head_r, head_c[1] - head_r * 1.25, head_c[0] + head_r,
           head_c[1] + head_r * 0.2), 170, 355, cap)                      # cap dome
    c.poly([(head_c[0] + head_r * 0.1, head_c[1] - head_r * 0.35),
            (head_c[0] + head_r * 1.5, head_c[1] - head_r * 0.15),
            (head_c[0] + head_r * 0.3, head_c[1] - head_r * 0.05)], cap)    # brim
    c.poly([(head_c[0] - head_r * 0.95, head_c[1] - head_r * 0.1),
            (head_c[0] - head_r * 0.45, head_c[1] - head_r * 0.5),
            (head_c[0] - head_r * 0.6, head_c[1] + head_r * 0.35)], hair)   # sideburn
    ex, ey = head_c[0] + head_r * 0.28, head_c[1] + head_r * 0.02
    c.ellipse((ex - 1, ey - 1.6, ex + 1.2, ey + 1.6), WHITE)
    c.rect((ex + 0.2, ey - 1, ex + 1.2, ey + 1), EYE)
    c.ellipse((head_c[0] + head_r * 0.55, head_c[1] + head_r * 0.12,
               head_c[0] + head_r * 1.15, head_c[1] + head_r * 0.5), SKIN_D)  # nose
    c.line([(head_c[0] - head_r * 0.1, head_c[1] + head_r * 0.55),
            (head_c[0] + head_r * 0.9, head_c[1] + head_r * 0.5)], 1.4, HAIR)  # 'stache
    _limb(c, (shoulder[0] + w * 0.16, shoulder[1]), P(pose["arm_f"]), h * 0.14, shirt, WHITE)
    if pose.get("extra") == "cap_spin":
        c.arc((head_c[0] - head_r * 1.4, head_c[1] - head_r * 1.4,
               head_c[0] + head_r * 1.4, head_c[1] + head_r * 0.2), 0, 300, 1.6, WHITE)
    return c


def _cycle(n, amp, phase=0.0, base_f=(0.62, 0.98), base_b=(0.40, 0.98)):
    """Hand/foot anchors swinging with stride phase, used by run/walk."""
    out = []
    for i in range(n):
        s = math.sin(2 * math.pi * (i / n + phase))
        s2 = math.cos(2 * math.pi * (i / n + phase))
        out.append(dict(leg_f=(base_f[0] + s * amp, base_f[1] - abs(s) * 0.10),
                        leg_b=(base_b[0] - s * amp, base_b[1] - abs(s2) * 0.06),
                        arm_f=(0.5 - s * 0.16, 0.62), arm_b=(0.5 + s * 0.14, 0.60),
                        hip=(0.5, 0.70 - abs(s2) * 0.015), lean=s2 * 0.05))
    return out


STAND = dict(leg_f=(0.60, 0.98), leg_b=(0.42, 0.98), arm_f=(0.70, 0.66), arm_b=(0.32, 0.64))
CROUCH = dict(leg_f=(0.66, 0.97), leg_b=(0.38, 0.97), arm_f=(0.74, 0.74), arm_b=(0.30, 0.72),
             hip=(0.5, 0.78))
JUMP = dict(leg_f=(0.66, 0.86), leg_b=(0.40, 0.96), arm_f=(0.80, 0.30), arm_b=(0.30, 0.52),
            hip=(0.5, 0.68), lean=0.04)
FALL = dict(leg_f=(0.64, 0.96), leg_b=(0.36, 0.90), arm_f=(0.78, 0.44), arm_b=(0.26, 0.52),
            hip=(0.5, 0.70))
SKID = dict(leg_f=(0.66, 0.98), leg_b=(0.30, 0.98), arm_f=(0.24, 0.50), arm_b=(0.72, 0.58),
            hip=(0.52, 0.72), lean=-0.10)
THROW = dict(leg_f=(0.64, 0.97), leg_b=(0.36, 0.97), arm_f=(0.86, 0.34), arm_b=(0.30, 0.58),
             hip=(0.5, 0.70), lean=0.05)
SWIM = [dict(leg_f=(0.66, 0.90), leg_b=(0.36, 0.96), arm_f=(0.82, 0.30), arm_b=(0.26, 0.60),
             hip=(0.5, 0.70), lean=0.06)]
SPIN = [dict(leg_f=(0.60, 0.92), leg_b=(0.42, 0.92), arm_f=(0.78, 0.40), arm_b=(0.24, 0.44),
             hip=(0.5, 0.72), lean=0.10, extra="cap_spin") for _ in range(2)]
DIVE = dict(leg_f=(0.72, 0.86), leg_b=(0.30, 0.92), arm_f=(0.16, 0.52), arm_b=(0.28, 0.44),
            hip=(0.54, 0.74), lean=-0.16)


FORMS = {
    "small": dict(h=14, shirt=RED, over=BLUE),
    "super": dict(h=22, shirt=RED, over=BLUE),
    "fire": dict(h=22, shirt=hexc("#f2f0ea"), over=RED),
    "ice": dict(h=22, shirt=hexc("#f0f6ff"), over=hexc("#3a7fd0")),
    "propeller": dict(h=22, shirt=hexc("#f2a33a"), over=hexc("#f2f0ea"),
                      cap=hexc("#e8c04a")),
    "penguin": dict(h=22, shirt=hexc("#27436e"), over=hexc("#141d30"),
                    cap=hexc("#1a2540")),
    "mini": dict(h=10, shirt=RED, over=BLUE),
    "mega": dict(h=26, shirt=hexc("#e8d44a"), over=hexc("#c9442a")),
}
CYCLES = {
    "idle": _cycle(1, 0.02),
    "walk": _cycle(4, 0.10),
    "run": _cycle(6, 0.16, phase=0.1),
    "crawl": [CROUCH],
    "jump": [JUMP],
    "fall": [FALL],
    "skid": [SKID],
    "throw": [THROW],
    "swim": SWIM,
    "spin": SPIN,
    "dive": [DIVE],
}


def _frames(poses, cfg):
    return [plumber(cfg["h"], {**STAND, **p}, cfg["shirt"], cfg["over"]) for p in poses]


for _form, _cfg in FORMS.items():
    for _anim, _poses in CYCLES.items():
        register(f"hero.{_form}.{_anim}", _frames, poses=_poses, cfg=_cfg,
                 frames=len(_poses), finish={"outline": 1.0, "rim": 0.26})
